apiVersion: v1
kind: Service
metadata:
  name: service-nginx-1
  namespace: lab1
spec:
  type: NodePort
  ports:           
        - targetPort: 80
          port: 80
          nodePort: 30001
  selector:
    app: myapp-nginx-1